/* tslint:disable */
/* eslint-disable */
/**
 * Bookstore - Server
 * Service that exposes the Bookstore API via REST
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetData
 */
export interface GetData {
    /**
     * 
     * @type {string}
     * @memberof GetData
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof GetData
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GetData
     */
    dateOfPublication?: string;
    /**
     * 
     * @type {string}
     * @memberof GetData
     */
    synopsis?: string;
    /**
     * 
     * @type {number}
     * @memberof GetData
     */
    numberOfPages?: number;
    /**
     * 
     * @type {string}
     * @memberof GetData
     */
    authors?: string;
}

/**
 * Check if a given object implements the GetData interface.
 */
export function instanceOfGetData(value: object): value is GetData {
    return true;
}

export function GetDataFromJSON(json: any): GetData {
    return GetDataFromJSONTyped(json, false);
}

export function GetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetData {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'title': json['title'] == null ? undefined : json['title'],
        'dateOfPublication': json['dateOfPublication'] == null ? undefined : json['dateOfPublication'],
        'synopsis': json['synopsis'] == null ? undefined : json['synopsis'],
        'numberOfPages': json['numberOfPages'] == null ? undefined : json['numberOfPages'],
        'authors': json['authors'] == null ? undefined : json['authors'],
    };
}

export function GetDataToJSON(json: any): GetData {
    return GetDataToJSONTyped(json, false);
}

export function GetDataToJSONTyped(value?: GetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'title': value['title'],
        'dateOfPublication': value['dateOfPublication'],
        'synopsis': value['synopsis'],
        'numberOfPages': value['numberOfPages'],
        'authors': value['authors'],
    };
}

