/* tslint:disable */
/* eslint-disable */
/**
 * Bookstore - Server
 * Service that exposes the Bookstore API via REST
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetListedData
 */
export interface GetListedData {
    /**
     * 
     * @type {string}
     * @memberof GetListedData
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof GetListedData
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof GetListedData
     */
    authors?: string;
}

/**
 * Check if a given object implements the GetListedData interface.
 */
export function instanceOfGetListedData(value: object): value is GetListedData {
    return true;
}

export function GetListedDataFromJSON(json: any): GetListedData {
    return GetListedDataFromJSONTyped(json, false);
}

export function GetListedDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListedData {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'title': json['title'] == null ? undefined : json['title'],
        'authors': json['authors'] == null ? undefined : json['authors'],
    };
}

export function GetListedDataToJSON(json: any): GetListedData {
    return GetListedDataToJSONTyped(json, false);
}

export function GetListedDataToJSONTyped(value?: GetListedData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'title': value['title'],
        'authors': value['authors'],
    };
}

